In [9]:
import pandas as pd
from src.preprocess import preprocess_text

df = pd.read_csv(r"C:\Users\aadhi\Desktop\Projects\Fake_News_Detection\data\processed\combined.csv")
df
#clean pipe
# remove very small text
# to csv

                                                    text  label
0      Donald Trump s White House is in chaos, and th...      0
1      Now that Donald Trump is the presumptive GOP n...      0
2      Mike Pence is a huge homophobe. He supports ex...      0
3      SAN FRANCISCO (Reuters) - California Attorney ...      1
4      Twisted reasoning is all that comes from Pelos...      0
...                                                  ...    ...
44893  ABUJA (Reuters) - The United States has formal...      1
44894  Tune in to the Alternate Current Radio Network...      0
44895   I m convinced the Freedom From Religion group...      0
44896  WASHINGTON (Reuters) - The Republican tax plan...      1
44897  SYDNEY (Reuters) - The U.N. High Commissioner ...      1

[44898 rows x 2 columns]

In [10]:
df['cleaned_text'] = df['text'].apply(preprocess_text)

In [11]:
df = df[df['cleaned_text'].str.len() > 20]
df.head(10)

,text,label,cleaned_text
0,"Donald Trump s White House is in chaos, and th...",0,donald trump white house chaos trying cover ru...
1,Now that Donald Trump is the presumptive GOP n...,0,donald trump presumptive gop nominee time reme...
2,Mike Pence is a huge homophobe. He supports ex...,0,mike penny huge homophobe support exgay conver...
3,SAN FRANCISCO (Reuters) - California Attorney ...,1,san francisco reuters california attorney gene...
4,Twisted reasoning is all that comes from Pelos...,0,twisted reasoning come pelosi day especially p...
5,WASHINGTON (Reuters) - As a lawyer in private ...,1,washington reuters lawyer private practice dec...
6,ADEN (Reuters) - A Salafist imam was shot dead...,1,aden reuters salafist imam shot dead gunman ea...
7,KUALA LUMPUR (Reuters) - Potential witnesses t...,1,kuala lumpur reuters potential witness multibi...
8,The goal of socialism is communism. -Vladimi...,0,goal socialism communism vladimir lenin commun...
9,Opposing views and beliefs has much of this co...,0,opposing view belief much country heated feud ...

In [12]:
df.to_csv(r"C:\Users\aadhi\Desktop\Projects\Fake_News_Detection\data\processed\preprocessed_data.csv", index=False)